name: Review

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup PHP Action
        # You may pin to the exact commit or the version.
        # uses: shivammathur/setup-php@3f36c0511e6b5c06cdbb82f098b7a32ccf1a1203
        uses: shivammathur/setup-php@2.9.0
        with:
          php-version: '7.3'

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
          
      - name: test
        run: |
          composer --working-dir=$GITHUB_WORKSPACE/php install
          composer --working-dir=$GITHUB_WORKSPACE/php run psalm |reviewdog -f psalm -fail-on-error -reporter
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
