name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: set
        run: |
          ENVS=$(cat << EOF
          APP_MODE=PREVIEW
          PR_NUMBER=100
          EOF
          )
          echo "ENVS<<EOF" >> $GITHUB_ENV
          echo "$ENVS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: check
        shell: bash
        run: |
          FOO=$(printf "%s" $ENVS |sed ':a;N;$!ba;s/\n/,/g')
          echo $FOO
