name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set common environment variables
        id: env-vars
        run: |
          cat << EOF > common.env.yaml
          KEY: VAL
          EOF
          cp common.env.yaml test.env.yaml
          echo "FOO: BAR" >> test.env.yaml
      
      - name: check
        run: |
          ls
          cat common.env.yaml
          cat test.env.yaml
