name: test

on:
  push:

jobs:
  test:
    environment: check
    runs-on: ubuntu-latest
    steps:
      - name: check variable
        uses: ./github/actions/test
        with:
          environment: test
